// Copyright 2020, Verizon Media
// Licensed under the terms of the MIT. See LICENSE file in project root for terms.

const supportedLanguages: Array<{name: string, value: string}> = [
  { name: "Plain Text",           value: ""             },
  { name: "ABAP",                 value: "abap"         },
  { name: "ActionScript",         value: "actionscript" },
  { name: "Ada",                  value: "ada"          },
  { name: "C / C++",              value: "c_cpp"        },
  { name: "C#",                   value: "csharp"       },
  { name: "COBOL",                value: "cobol"        },
  { name: "D",                    value: "d"            },
  { name: "Dart",                 value: "dart"         },
  { name: "Delphi/Object Pascal", value: "pascal"       },
  { name: "Dockerfile",           value: "dockerfile"   },
  { name: "Elixir",               value: "elixir"       },
  { name: "Elm",                  value: "elm"          },
  { name: "Erlang",               value: "erlang"       },
  { name: "F#",                   value: "fsharp"       },
  { name: "Fortran",              value: "fortran"      },
  { name: "Go",                   value: "golang"       },
  { name: "Groovy",               value: "groovy"       },
  { name: "Haskell",              value: "haskell"      },
  { name: "Java",                 value: "java"         },
  { name: "JavaScript",           value: "javascript"   },
  { name: "Julia",                value: "julia"        },
  { name: "Kotlin",               value: "kotlin"       },
  { name: "Lisp",                 value: "lisp"         },
  { name: "Lua",                  value: "lua"          },
  { name: "MATLAB",               value: "matlab"       },
  { name: "Markdown",             value: "markdown"     },
  { name: "Objective-C",          value: "objectivec"   },
  { name: "PHP",                  value: "php"          },
  { name: "Perl",                 value: "perl"         },
  { name: "Prolog",               value: "prolog"       },
  { name: "Properties",           value: "properties"   },
  { name: "Python",               value: "python"       },
  { name: "R",                    value: "r"            },
  { name: "Ruby",                 value: "ruby"         },
  { name: "Rust",                 value: "rust"         },
  { name: "SQL",                  value: "sql"          },
  { name: "Sass",                 value: "sass"         },
  { name: "Scala",                value: "scala"        },
  { name: "Scheme",               value: "scheme"       },
  { name: "Shell/Bash",           value: "sh"           },
  { name: "Swift",                value: "swift"        },
  { name: "Tcl",                  value: "tcl"          },
  { name: "Terraform",            value: "terraform"    },
  { name: "Toml",                 value: "toml"         },
  { name: "TypeScript",           value: "typescript"   },
  { name: "VBScript",             value: "vbscript"     },
  { name: "XML",                  value: "xml"          },
]

export default supportedLanguages
