FROM golang:1.21-alpine

RUN apk add --no-cache git inotify-tools g++ && \
    rm -rf /var/cache/apk/*

RUN mkdir /typescript-dtos
RUN mkdir /app
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

RUN go get -v github.com/rubenv/sql-migrate/...

CMD ["backend/run-dev.sh"]
