FROM golang:1.20.11-alpine

RUN apk add --no-cache git inotify-tools g++ && \
    rm -rf /var/cache/apk/* && \
    go install -v github.com/rubenv/sql-migrate/sql-migrate@v1.1.0

RUN mkdir /typescript-dtos
RUN mkdir /app
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

CMD ["backend/run-dev.sh"]
