FROM golang:1.21-alpine AS build

RUN apk add --no-cache git && \
    rm -rf /var/cache/apk/*

RUN mkdir /build
WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY backend backend
COPY signer signer
RUN go build -gcflags "all=-N -l" ./backend/bin/web/


FROM alpine:latest

RUN apk add --no-cache ca-certificates delve && \
    adduser -h /home/ashirt -S -D ashirt

USER ashirt
WORKDIR /home/ashirt

COPY --from=build /build/web /home/ashirt/public-api
COPY backend/migrations /migrations

CMD dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec /home/ashirt/public-api --continue
