version: "3"
services:
  ashirt-private-service:
    build:
      context: .
      dockerfile: Dockerfile.prod.web
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      APP_CSRF_AUTH_KEY: "dummy-csrf-for-testing-prod-locally"
      APP_IMGSTORE_BUCKET_NAME: ""
      APP_IMGSTORE_REGION: ""
      APP_PORT: 8000
      APP_SESSION_STORE_KEY: "dummy-session-key-for-testing-prod-locally"
      AUTH_OKTA_BACKEND_URL: "http://localhost:8080/web"
      AUTH_OKTA_CLIENT_ID: 
      AUTH_OKTA_CLIENT_SECRET: 
      AUTH_OKTA_FAILURE_REDIRECT_URL_PREFIX: "http://localhost:8080"
      AUTH_OKTA_ISSUER: 
      AUTH_OKTA_PROFILE_TO_SHORTNAME_FIELD: preferred_username
      AUTH_OKTA_SUCCESS_REDIRECT_URL: "http://localhost:8080"
      AUTH_SERVICES: ashirt
      DB_URI: dev-user:dev-user-password@tcp(db:3306)/dev-db


  ashirt-public-service:
    build:
      context: .
      dockerfile: Dockerfile.prod.api
    ports:
      - 8001:8000
    restart: on-failure
    environment:
      APP_IMGSTORE_BUCKET_NAME: ""
      APP_IMGSTORE_REGION: ""
      APP_PORT: 8000
      DB_URI: dev-user:dev-user-password@tcp(db:3306)/dev-db


  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod.frontend
    ports:
      - 8080:8080


  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./dev_seed_data/z01_seed_data.sql:/docker-entrypoint-initdb.d/z01_seed_data.sql
      - ./dev_seed_data/z02_gantt_operation.sql:/docker-entrypoint-initdb.d/z02_gantt_operation.sql
    environment:
      - MYSQL_DATABASE=dev-db
      - MYSQL_ROOT_PASSWORD=dev-root-password
      - MYSQL_USER=dev-user
      - MYSQL_PASSWORD=dev-user-password
